version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo hello world
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/netflix-eureka-naming-server-0.0.1-SNAPSHOT.jar